### ISSUE TITLE
DuckDuckGo language setting cannot be disabled 

### ISSUE THREAD

**Issue by craigmiskell** [craigmiskell/cookiemaster#18]
From https://github.com/craigmiskell/cookiemaster/issues/15#issuecomment-613465157
"There is also a bug if cookies are enabled with your addon on DuckDuckGo: once we enable the language change, we cannot disable it."

**Comment by craigmiskell** [comment]
It was an awful bug in the code that prevented cookies being *deleted* by javascript.  

Fixed in 1.1.5, just released (should be available soon)

**Comment by baptx** [comment]
@craigmiskell I tested with the new version, now we can change the language if cookies are enabled but we still cannot change the language if cookies are disabled.

**Comment by craigmiskell** [comment]
Great.

**Comment by baptx** [comment]
@craigmiskell I meant the bug is still here when cookies are disabled so I think you can reopen this issue (it is only partially fixed).

**Comment by craigmiskell** [comment]
That sounds like a different issue, and it might not be a straight up bug, just something that happens when cookies are blocked.  I'll open a separate issue for that.

**Comment by craigmiskell** [comment]
https://github.com/craigmiskell/cookiemaster/issues/19
